pipeline {

    agent any
    
    tools {
        gradle 'gradle-8.2.1'
        jdk 'jdk-11'
        dockerTool 'docker'
    }

    stages {
        stage('Clear current directory') {
            steps {
                sh'''
                    rm -rf *
                '''
            }
        }

        
        stage('Pull from GitLab') {
            steps {
                git url: 'https://lab.ssafy.com/s09-fintech-finance-sub2/S09P22A607.git',
                    branch: 'feat/70',
                    credentialsId: 'ab6625fd-a8a2-4a73-a301-bd4f0edbb103'
            }
        }

        stage('Apply application.yml files') {
            steps {
                withCredentials([file(credentialsId: 'application-secret', variable: 'secretFile'),
                                file(credentialsId: 'application-develop', variable: 'developFile')]) {
                    script {
                        sh 'cp $secretFile backend/src/main/resources/application-secret.yml'
                        sh 'cp $developFile backend/src/main/resources/application-develop.yml'
                    }
                }
            }
        }

        stage('Build Backend') {
            steps {
                dir('backend') {
                    sh'''
                        gradle wrapper
                        chmod +x gradlew
                        ./gradlew clean build -x test --stacktrace
                    '''
                }
            }
        }

        // stage('SonarQube Analysis') {
        //     steps {
        //         withSonarQubeEnv('SonarQube-haruman') { 
        //             dir('backend') {
        //                 sh './gradlew sonarqube --stacktrace'
        //             }
        //         }
        //     }
        // }

        stage('Delete existing Docker images and containers') {
            steps {
                sh'''
                    if docker container inspect haruman_server >/dev/null 2>&1; then
                        echo "container exists locally"
                        docker stop haruman_server
                        docker rm haruman_server
                    else
                        echo "container does not exist locally"
                    fi
                    if docker image inspect server >/dev/null 2>&1; then
                        echo "Image exists locally"
                        docker rmi server 
                    else
                        echo "Image does not exist locally"
                    fi
                '''
            }
        }

        // stage('Zero Downtime Deployment') {
        //     steps {
        //         sh'''
        //             echo "\n****** Blue Health Check & Build ******"

        //             if curl -s "http://3.34.135.50:8081" > /dev/null
        //             then
        //                 deployment_target_port=8082
        //                 deployment_target=green
        //             else
        //                 deployment_target_port=8081
        //                 deployment_target=blue
        //             fi

        //             echo [BE] Green Build Docker Image!
        //             docker build -t server ./backend
        //             echo [BE] Green Run Docker Container!
        //             docker run -dp ${deployment_target_port}:8081 --name haruman_server_${deployment_target} server
 


        //             echo "\n****** Continuous Green Health Check ******"

        //             for retry_count in \$(seq 10)
        //             do
        //               if curl -s "http://3.34.135.50:${deployment_target_port}" > /dev/null
        //               then
        //                   echo "Health check success ✅"
        //                   break
        //               fi

        //               if [ $retry_count -eq 10 ]
        //               then
        //                 echo "Health check failed ❌"
        //                 exit 1
        //               fi

        //               echo "The server is not alive yet. Retry health check in 10 seconds..."
        //               sleep 10
        //             done



        //             echo "\n****** Nginx Proxy Redirect & Kill Blue ******"

        //             ssh root@3.34.135.50:80 "echo 'set \\haruman.site http://3.34.135.50:${deployment_target_port};' > /etc/nginx/conf.d/service-url.inc && service nginx reload"
        //             echo "Switch the reverse proxy direction of nginx to http://3.34.135.50:${deployment_target_port} 🔄"

        //             if [ "${deployment_target}" == blue ]
        //             then
        //                 ssh root@${green_ip} "fuser -s -k 8081/tcp"
        //             else
        //                 ssh root@${blue_ip} "fuser -s -k 8081/tcp"
        //             fi
        //             echo "Kill the process on the opposite server."
        //         '''
        //     }
        // }

        stage('Build and Deploy Docker') {
            steps {
                dir('backend') {
                    sh'''
                        echo [BE] Build Docker Image!
                        docker build -t server .
                        echo [BE] Run Docker Container!
                        docker run -dp 8081:8081 --name haruman_server server
                    '''
                }
            }
        }
    }

    post {
        success {
            script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                def GIT_COMMIT_MSG = sh(script: 'git log -1 --pretty=%B ${GIT_COMMIT}', returnStdout: true).trim()
                mattermostSend(color: 'good', message: "✅ 빌드 & 배포 성공: ${env.JOB_NAME} (<${env.BUILD_URL}|#${env.BUILD_NUMBER}>)\n브랜치: be/develop\n커밋 메시지: ${GIT_COMMIT_MSG} by ${Author_ID}(${Author_Name})")
            }
        }
        failure {
            script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                def GIT_COMMIT_MSG = sh(script: 'git log -1 --pretty=%B ${GIT_COMMIT}', returnStdout: true).trim()
                mattermostSend(color: 'danger', message: "❌ 빌드 & 배포 실패: ${env.JOB_NAME} (<${env.BUILD_URL}|#${env.BUILD_NUMBER}>)\n브랜치: be/develop\n커밋 메시지: ${GIT_COMMIT_MSG} by ${Author_ID}(${Author_Name})")
            }
        }
    }
}